#!/bin/bash
set -e              # exit on error
set -u              # exit on undefined variable
set -o pipefail     # propagate nonzero exit codes through pipelines

while read dep; do
    echo "fetching: ${dep}" >&2
    echo "${dep} LICENSE file:"
    echo ""
    curl --silent "https://hackage.haskell.org/package/${dep}/src/LICENSE" \
        | sed 's/^/  /g' # indent by 2 characters
    echo ""
done
