resolver: lts-16.17
pvp-bounds: upper
packages:
- '.'
- lib/purescript-ast
- lib/purescript-cst
extra-deps:
- serialise-0.2.2.0
- cborg-0.2.2.0
- happy-1.20.0
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
nix:
  enable: false
  packages:
  - zlib
  # Test dependencies
  - nodejs
  - nodePackages.npm
  - nodePackages.bower
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
    quickcheck: false
