# Please update Haskell image versions under .github/workflows/ci.yml together to use the same GHC version
# (or the CI build will fail)
resolver: nightly-2022-06-06
pvp-bounds: both
packages:
- '.'
ghc-options:
  # Build with advanced optimizations enabled by default
  "$locals": -O2 -Werror
extra-deps:
# As of 2021-11-08, the latest release of `language-javascript` is 0.7.1.0,
# but it has a problem with parsing the `async` keyword.  It doesn't allow
# `async` to be used as an object key:
# https://github.com/erikd/language-javascript/issues/131
- language-javascript-0.7.0.0
# Fix issue with libtinfo.
# See https://github.com/purescript/purescript/issues/4253
- process-1.6.13.1
# The Cabal library is not in Stackage
- Cabal-3.6.3.0
# Protolude is not yet in resolver snapshot
- protolude-0.3.1
nix:
  packages:
  - zlib
  # Test dependencies
  - nodejs
  - nodePackages.npm
  - nodePackages.bower
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
  haskeline:
    # Avoids a libtinfo dynamic library dependency
    terminfo: false
