# Please update Haskell image versions under .github/workflows/ci.yml together to use the same GHC version
# (or the CI build will fail)
resolver: lts-22.43
pvp-bounds: both
packages:
- '.'
ghc-options:
  # Build with advanced optimizations enabled by default
  "$locals": -O2 -Werror
extra-deps:
# As of 2021-11-08, the latest release of `language-javascript` is 0.7.1.0,
# but it has a problem with parsing the `async` keyword.  It doesn't allow
# `async` to be used as an object key:
# https://github.com/erikd/language-javascript/issues/131
- language-javascript-0.7.0.0
- bower-json-1.1.0.0
- haskeline-0.8.2
- these-1.2.1
- aeson-better-errors-0.9.1.3

- github: purescript/cheapskate
  commit: 8bfaf4beeb108e97a274ed51303f278905979e87

nix:
  packages:
  - zlib
  # Test dependencies
  - nodejs
  - nodePackages.npm
  - nodePackages.bower
flags:
  aeson-pretty:
    lib-only: true
  haskeline:
    # Avoids a libtinfo dynamic library dependency
    terminfo: false

allow-newer: true
allow-newer-deps:
- haskeline
