resolver: lts-13.26
pvp-bounds: upper
packages:
- '.'
extra-deps:
- network-3.0.1.1
- language-javascript-0.6.0.13
nix:
  enable: false
  packages:
  - zlib
  # Test dependencies
  - nodejs
  - nodePackages.npm
  - nodePackages.bower
flags:
  aeson-pretty:
    lib-only: true
